{
  config,
  lib,
  pkgs,
  inputs,
  ...
}:

let
  # Offizielles Discord mit Vencord statt Vesktop: Anrufe, Kamera und
  # Bildschirmfreigabe laufen über Discords eigene Audio/Video-Engine
  # (discord_voice) wie unter Windows, nicht über Chromiums WebRTC. In
  # Vesktop froren eingehende Kameras alle paar Sekunden für 2–3 s ein.
  # Wayland-Flags setzt das Paket selbst (NIXOS_OZONE_WL, desktop.nix).
  #
  # Läuft auf der Intel-iGPU (wie früher Vesktop): Systemweit zeigt VA-API
  # auf nvidia-vaapi-driver (nvidia.nix), der nur dekodieren kann. Auf der
  # NVIDIA stürzte Discords GPU-Prozess ab, sobald Kamera oder Stream an
  # gingen. Die Iris Xe kodiert/dekodiert H.264, H.265 und VP9 in Hardware
  # (intel-media-driver), AV1 nur dekodieren.
  # CUDA_VISIBLE_DEVICES versteckt die NVIDIA zusätzlich vor Discords eigener
  # Engine: Sonst kodiert sie Kamera und Stream per NVENC (CUDA, H.265) und
  # stürzte dabei ab. Ohne CUDA nimmt sie H.264 per VA-API auf der Iris Xe.
  #
  # Ausnahme Hyprland: Es rendert auf der NVIDIA und kann die Bildpuffer der
  # iGPU nicht importieren (eglCreateImageKHR: „buffer attributes are not
  # supported“) → Discord-Fenster bleibt schwarz. Dort zeichnet Discord daher
  # auf der NVIDIA.
  #
  # Ausnahme Niri: Niri rendert ebenfalls auf der NVIDIA und liefert den
  # Bildschirm-Stream nur als DMA-BUF mit NVIDIA-Modifiern (kein MemFd).
  # Discord nimmt nur Puffer der GPU an, mit der es auch kodiert – ohne CUDA
  # wäre das die Iris Xe (Intel-Modifier) → „no more input formats“, Stream
  # bricht sofort ab. Unter Niri bleibt CUDA daher sichtbar (NVENC kodiert).
  # Falls Discord dabei wieder in libcuda abstürzt: ScreenCast-Portal unter
  # Niri auf xdg-desktop-portal-wlr umstellen (bietet MemFd an).
  discordVencord = pkgs.discord.override {
    withVencord = true;
  };
  discord = pkgs.symlinkJoin {
    name = "discord-igpu";
    paths = [ discordVencord ];
    nativeBuildInputs = [ pkgs.makeWrapper ];
    postBuild = ''
      for bin in discord Discord; do
        rm $out/bin/$bin
        makeWrapper ${discordVencord}/bin/$bin $out/bin/$bin \
          --set LIBVA_DRIVER_NAME iHD \
          --prefix LD_LIBRARY_PATH : ${lib.getLib pkgs.libva}/lib \
          --run 'render_node=/dev/dri/intel-render; export CUDA_VISIBLE_DEVICES=-1' \
          --run 'if [ -n "''${HYPRLAND_INSTANCE_SIGNATURE:-}" ]; then render_node=/dev/dri/nvidia-render; fi' \
          --run 'if [ -n "''${NIRI_SOCKET:-}" ]; then render_node=/dev/dri/nvidia-render; unset CUDA_VISIBLE_DEVICES; fi' \
          --add-flags '--render-node-override=$render_node'
      done
    '';
  };

  # ATAS X auf der RTX 4060: Oberfläche (Avalonia/Skia) und Charts (eigener
  # Renderer) zeichnen per OpenGL über GLX (XWayland). Klappt GLX nicht,
  # rendert Avalonia still auf der CPU weiter → DOM/Tape ruckeln.
  # Die Variablen sind die von `nvidia-offload`: GLX/Vulkan fest auf NVIDIA,
  # egal auf welcher GPU XWayland gerade läuft. Prüfen: `nvidia-smi` listet
  # dann den Prozess „ATAS X“.
  atasXUnwrapped = pkgs.callPackage ../../pkgs/atas-x/package.nix { };
  atasX = pkgs.symlinkJoin {
    name = "atas-x-nvidia";
    paths = [ atasXUnwrapped ];
    nativeBuildInputs = [ pkgs.makeWrapper ];
    postBuild = ''
      rm $out/bin/atas-x
      makeWrapper ${atasXUnwrapped}/bin/atas-x $out/bin/atas-x \
        --set __NV_PRIME_RENDER_OFFLOAD 1 \
        --set __NV_PRIME_RENDER_OFFLOAD_PROVIDER NVIDIA-G0 \
        --set __GLX_VENDOR_LIBRARY_NAME nvidia \
        --set __VK_LAYER_NV_optimus NVIDIA_only
    '';
  };

  # Firefox-Farben aus dem Hintergrundbild: Die Erweiterung Pywalfox fragt
  # über Native Messaging dieses Programm, das ~/.cache/wal/colors.json liest
  # (erzeugt von matugen, siehe matugen/config.toml). Das Paket bringt die
  # Manifest-Datei für Firefox nicht mit, daher hier selbst.
  pywalfoxHost =
    let
      start = pkgs.writeShellScript "pywalfox-host" ''
        exec ${pkgs.pywalfox-native}/bin/pywalfox start
      '';
    in
    pkgs.writeTextDir "lib/mozilla/native-messaging-hosts/pywalfox.json" (
      builtins.toJSON {
        name = "pywalfox";
        description = "Automatically theme your browser using the colors generated by Pywal";
        path = "${start}";
        type = "stdio";
        allowed_extensions = [ "pywalfox@frewacom.org" ];
      }
    );
in
{
  imports = [ inputs.spicetify-nix.nixosModules.default ];

  # ── Firefox ────────────────────────────────────────────────
  programs.firefox = {
    enable = true;
    languagePacks = [
      "de"
      "en-US"
    ];
    preferencesStatus = "default"; # nur Voreinstellungen, in about:config änderbar
    preferences = {
      # Hardware-Videodekodierung über VA-API (NVIDIA)
      "media.ffmpeg.vaapi.enabled" = true;
      "widget.dmabuf.force-enabled" = true; # nötig für VA-API auf NVIDIA
      # KDE-Dateidialog statt GTK
      "widget.use-xdg-desktop-portal.file-picker" = 1;
      "widget.use-xdg-desktop-portal.mime-handler" = 1;
      # Apple-Emoji statt des mitgelieferten Twemoji (siehe fonts.nix)
      "font.name-list.emoji" = "Apple Color Emoji";
      # Webseiten hell oder dunkel wie das System (theme.sh, 2 = wie Firefox)
      "layout.css.prefers-color-scheme.content-override" = 2;

      # ── Tempo (Werte wie Betterfox „Fastfox“) ──
      # Seiten früher zeichnen statt auf mehr Inhalt zu warten
      "content.notify.interval" = 100000;
      # Mehr parallele Verbindungen, keine künstliche Drosselung
      "network.http.max-connections" = 1800;
      "network.http.max-persistent-connections-per-server" = 10;
      "network.http.max-urgent-start-excessive-connections-per-host" = 5;
      "network.http.pacing.requests.enabled" = false;
      # DNS-Antworten und TLS-Sitzungen länger merken (jede DNS-Anfrage
      # geht sonst durch den VPN-Tunnel, ~40 ms)
      "network.dnsCacheExpiration" = 3600;
      "network.ssl_tokens_cache_capacity" = 10240;
      # Größere Caches im RAM (16 GB sind genug da)
      "browser.cache.memory.capacity" = 131072; # 128 MB
      "browser.cache.memory.max_entry_size" = 20480;
      "media.memory_cache_max_size" = 65536;
      "media.cache_readahead_limit" = 7200; # Videos weiter vorpuffern
      "media.cache_resume_threshold" = 3600;
      "image.mem.decode_bytes_at_a_time" = 32768;
      "gfx.canvas.accelerated.cache-size" = 512;
      "gfx.content.skia-font-cache-size" = 20;
      # Sitzung seltener auf die SSD schreiben (15 s → 60 s)
      "browser.sessionstore.interval" = 60000;
    };
    # Weniger Hintergrundverkehr und Arbeit im Browser
    policies = {
      DisableTelemetry = true;
      DisableFirefoxStudies = true;
      # Pywalfox: Farben von matugen (pywalfoxHost oben), wird automatisch
      # installiert, lässt sich aber wie jede Erweiterung abschalten
      ExtensionSettings."pywalfox@frewacom.org" = {
        installation_mode = "normal_installed";
        install_url = "https://addons.mozilla.org/firefox/downloads/latest/pywalfox/latest.xpi";
      };
    };
    nativeMessagingHosts.packages = [ pywalfoxHost ];
  };

  # ── Messenger, Musik, KI-Tools ──────────────────────────────────────
  environment.systemPackages = with pkgs; [
    discord # mit Vencord, siehe oben
    telegram-desktop
    tradingview
    atasX # Orderflow-Analyse (Linux-Alpha), auf der NVIDIA, siehe oben
    vlc # Videoplayer
    easyeffects # Equalizer (AutoEQ-Profil für die KZ-IEMs)
    cameractrls-gtk4 # Webcam-Bild einstellen (Schärfe, Kontrast …) mit Live-Vorschau
    pywalfox-native # `pywalfox update` in matugen/theme.sh

    # KI-Coding-Tools im Terminal: `claude` (Claude Code), `agy` (Antigravity CLI).
    # Updates kommen über `rebuild update`, nicht über die eingebauten Updater.
    claude-code
    antigravity-cli

    # Claude Desktop (Linux-Beta, aus dem offiziellen .deb verpackt)
    (callPackage ../../pkgs/claude-desktop/package.nix { })
  ];

  # Stellt die in Cameractrls gespeicherten Webcam-Einstellungen wieder her
  # (nach dem Login und beim Einstecken), sonst setzt die Kamera sie zurück
  systemd.user.services.cameractrlsd = {
    description = "Webcam-Einstellungen wiederherstellen (cameractrls)";
    wantedBy = [ "graphical-session.target" ];
    partOf = [ "graphical-session.target" ];
    serviceConfig = {
      ExecStart = "${pkgs.cameractrls-gtk4}/bin/cameractrlsd";
      Restart = "on-failure";
    };
  };

  # Cowork in Claude Desktop startet Aufgaben in einer VM (QEMU/KVM)
  users.users.flask.extraGroups = [ "kvm" ];
  boot.kernelModules = [ "vhost_vsock" ];

  # ── Spotify + Spicetify ────────────────────────────────────
  # Ersetzt das normale Spotify-Paket. Spotifys eigenes Layout (Default-
  # Theme – bleibt mit jedem Spotify-Update heil; Comfy war seit 12/2025
  # nicht mehr aktuell und zerlegte die Oberfläche), Farben und die
  # Korrekturen für den Hellmodus aus matugen/templates/spicetify-colors.css.
  programs.spicetify =
    let
      spicePkgs = inputs.spicetify-nix.legacyPackages.${pkgs.stdenv.hostPlatform.system};
      matugenColors = "${config.users.users.flask.home}/.cache/matugen/spicetify-colors.css";
    in
    {
      enable = true;
      theme = spicePkgs.themes.default;
      colorScheme = "Ocean"; # nur für den Build, colors.css kommt von matugen
      # Spicetify schreibt die Farben beim Build fest in colors.css; ein
      # Symlink auf die Datei von matugen macht sie änderbar. postFixup läuft
      # nach dem `spicetify apply` in postInstall.
      spotifyPackage = pkgs.spotify.overrideAttrs (old: {
        dontCheckForBrokenSymlinks = true; # Ziel liegt außerhalb des Stores
        postFixup = (old.postFixup or "") + ''
          ln -sf ${matugenColors} $out/share/spotify/Apps/xpui/colors.css
        '';
      });
      # Neue Farben nach einem Hintergrundwechsel sofort übernehmen, ohne
      # Spotify neu zu starten (Datei ist klein, wird nur im Vordergrund geprüft)
      enabledExtensions = [
        {
          src = pkgs.writeTextDir "matugen-colors.js" ''
            (function matugenColors() {
              const link = document.querySelector("link.userCSS[href='colors.css']");
              if (!link) return setTimeout(matugenColors, 300);
              const style = document.createElement("style");
              link.after(style);
              let last;
              setInterval(async () => {
                if (document.hidden) return;
                try {
                  const res = await fetch("colors.css", { cache: "no-store" });
                  if (!res.ok) return;
                  const css = await res.text();
                  if (last !== undefined && css !== last) style.textContent = css;
                  last = css;
                } catch {}
              }, 2000);
            })();
          '';
          name = "matugen-colors.js";
        }
      ];
      enabledSnippets = [
        # Songtexte immer in den matugen-Farben statt einer Farbe pro Lied
        # (Spotify setzt die Variablen inline, daher !important)
        ''
          :root,
          [style*="--lyrics-color"] {
            --lyrics-color-background: var(--spice-main) !important;
            --lyrics-color-active: var(--spice-text) !important;
            --lyrics-color-passed: var(--spice-subtext) !important;
            --lyrics-color-inactive: rgba(var(--spice-rgb-subtext), 0.5) !important;
            --lyrics-color-messaging: var(--spice-subtext) !important;
          }
        ''
        # Minecraft-Schrift überall (Schriften kommen aus fonts.nix)
        ''
          :root {
            --encore-body-font-stack: "Minecraftia", "Monocraft", sans-serif !important;
            --encore-title-font-stack: "Minecraftia", "Monocraft", sans-serif !important;
            --encore-variable-font-stack: "Minecraftia", "Monocraft", sans-serif !important;
          }
          *:not([class*="spoticon"]) {
            font-family: "Minecraftia", "Monocraft", sans-serif !important;
          }
        ''
      ];
    };

  # Spotify Connect / Geräte im lokalen Netz finden
  networking.firewall = {
    allowedTCPPorts = [ 57621 ];
    allowedUDPPorts = [ 5353 ];
  };
}
