[main]
# This centers the launcher and makes it look more like a "Search" bar
width=30
tabs=4
horizontal-pad=20
vertical-pad=20
inner-pad=10

# ICON SETTINGS
# 'yes' shows icons. To get "Icons Only", we set the text color to transparent later.
show-actions=no
icon-theme=Yaru-dark
icons-enabled=yes
icon-size=64

# This makes it a grid-like feel
line-height=20
fields=name,generic

[colors]
background=1a1a1aff
text=ffffffff
selection=ffc87fff
selection-text=000000ff
border=ffc87fff

[border]
width=2
radius=16
